server:
  port: 3344
spring:
  application:
    name: xzyservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuzhiyong28/springcloud-config
          username: xuzhiyong28
          password: xzy531029750